### ISSUE TITLE
Criar endpoint para cadastro de proposta de consulta

### ISSUE THREAD

**Issue by Pedro-H-Nery** [ES2-UFPI/Seyfert#12]
#### Descrição sobre endpoint para cadastro de proposta de consulta
Um médico pode cadastrar quantas propostas quiser para diferentes solicitações seguindo as seguintes regras:
- RN01 - Uma proposta só pode ser considerada válida se o médico não tiver nenhuma consulta já marcada para o mesmo horário e data.
- NR002 - Uma proposta não pode ser cadastrada fora da data mostrada na solicitação.
   - Exemplos: Solicitação Ortopedia 20/01/2023 de 10:00 às 12:00. O médico não pode cadastrar uma proposta para o dia 19/01/2023 e nem 21/01/2023.  Embora possa cadastrar fora do horário especificado.
- RN03 - Em nenhuma hipótese um médico pode cadastrar propostas em especialidades que não sejam as suas.

**Comment by Mathwebb** [comment]
Já foi finalizada, porém não foi fechada
