### ISSUE TITLE
Criar endpoint para remoção de solicitação

### ISSUE THREAD

**Issue by Pedro-H-Nery** [ES2-UFPI/Seyfert#8]
#### Descrição sobre endpoint para remoção de solicitação.
Um paciente pode remover quanta solicitação quiser seguindo a seguintes regras:
- RN01 - A solicitação não pode está vencida

**Comment by jardessonribeiroTI** [comment]
Issue repriorizada para outro momento da sprint.

**Comment by jardessonribeiroTI** [comment]
Issue repriorizada para outro momento da sprint.
